name: ml
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - faiss-gpu
  - pip:
      - transformers==4.45.2
      - sentencepiece
      - tree-sitter==0.21.0
      - flask
      - gunicorn